

SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_CATALOG='Shop'
Order by TABLE_NAME

SELECT * FROM __EFMigrationsHistory
SELECT * FROM Catalogue
SELECT * FROM Product